### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by linkvapeluckyman** [patrick-kw-chiu/mongo-http.js#2]
//i have created worker.js like this

import { InitCollection, InsertOne, initDatabase  } from 'mongo-http';

// Initialize MongoDB collection
(async function() {
  // Initialize MongoDB collection
  const db = initDatabase({
    appId: 'myappid',
    apiKey: 'myapikey',
    databaseName: 'mydatabasename',
    //collectionName: 'videos',
  });
  
  const result = await db.collection('videos').insertOne({
   writerId: 'patrick-writer-object-id',
   title: 'Introducing mongo-http.js',
   tags: ['javascript', 'mongodb', 'serverless', 'nodejs', 'cloudflare-workers']
  });

// If the insertion is successful
// => isSuccess: true, insertedId: 'object-id'
  const { isSuccess, insertedId } = result;

  // If the insertion is successful
  // => isSuccess: true, insertedId: 'object-id'
  //const { isSuccess, insertedId } = result;

  // Rest of your code...

});

**Comment by patrick-kw-chiu** [comment]
What is the error you received?

**Comment by patrick-kw-chiu** [comment]
I'll close this issue for now. If you have any problem related to this issue, feel free to reopen.
